application: ctarcade
version: 2
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static
    
- url: /favicon.ico
  static_files: static/image/favicon.ico
  upload: static/image/favicon.ico
  
- url: .*
  script: main.py