application: ctarcade
version: 2
runtime: python
api_version: 1

handlers:

- url: /js
  static_dir: js
  
- url: /css
  static_dir: css

- url: /bootstrap
  static_dir: bootstrap

- url: /css/image
  static_dir: css/image

- url: /favicon.ico
  static_files: css/image/favicon.ico
  upload: css/image/favicon.ico
  
- url: .*
  script: main.py